decov:
  branch: master

coverage:
  precision: 2
  round: nearest
  range: "50...100"
  status:
    project:
      default:
        threshold: null
    patch:
      default:
        target: 80%
  ignore:
    - "modules/matrix"

comment:
  layout: "diff"